Add LanguageStandard. Breaks compiler! 1>------ Rebuild All started: Project: Vc141Boost171, Configuration: Release Win32 ------ 1>Source.cpp 1>Generating code 1>beasthttpsynccrash\packages\boost.1.71.0.0\lib\native\include\boost\beast\http\impl\serializer.hpp(54): fatal error C1001: An internal error has occurred in the compiler. 1>(compiler file 'd:\agent\_work\3\s\src\vctools\compiler\utc\src\p2\main.c', line 187) 1> To work around this problem, try simplifying or changing the program near the locations listed above. 1>Please choose the Technical Support command on the Visual C++ 1> Help menu, or open the Technical Support help file for more information 1>  link!CloseTypeServerPDB()+0x7e8e7 1>  link!CloseTypeServerPDB()+0x7e8e7 1>  link!CloseTypeServerPDB()+0xd73d 1> 1>Done building project "Vc141Boost171.vcxproj" -- FAILED. ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========